

services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      FLASK_ENV: development
      DATABASE_NAME: chirashi_dev_db

    working_dir: /backend
    command: bash -c "poetry install --no-root && poetry run flask --app main run  --host=0.0.0.0  --debug --port 8000"
    depends_on: 
      - mysql

  svelte-app:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ./frontend/:/frontend/
    
    working_dir: /frontend
    command: bash -c "yarn install && yarn run dev --host"
    environment:
      - NODE_ENV=development
      - PORT=5050
      - HOST=0.0.0.0


  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chirashi_dev_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    restart: always

volumes:
  mysql_dev_data:
