services:
  backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile

    restart: always
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development

      DATABASE_NAME: chirashi_prod_db
    working_dir: /backend
    command: bash -c "poetry run waitress-serve --host 0.0.0.0 --port 8000 main:app"
    depends_on: 
      - mysql

  svelte-app:
    build:
      context: ./frontend/
      dockerfile: prod.Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ./frontend/:/frontend/
    
    working_dir: /frontend
    command: bash -c " yarn run build && yarn run preview"
    environment:
      - NODE_ENV=production
      - PORT=5050
      - HOST=0.0.0.0

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chirashi_prod_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    restart: always

volumes:
  mysql_prod_data:
